### ISSUE TITLE
Build action - github pages not functioning correctly

### ISSUE THREAD

**Issue by dataforaction-tom** [Data-For-Action/local-needs-data-frontend#3]
@drkane - not sure the build action is functioning properly. Can you check?

**Comment by drkane** [comment]
@dataforaction-tom  Can confirm it's not updating to the latest version: https://data-for-action.github.io/local-needs-data-frontend/ is still serving out-of-date assets.

I can't change the settings for the repo. Can you double check that settings > pages is set to "Deploy from a branch" and that the branch is gh-pages ?

Should look something like this:
![image](https://github.com/Data-For-Action/local-needs-data-frontend/assets/1049910/f1a4d8e1-828d-445c-80d3-89581ed83489)

**Comment by tomcwxyz** [comment]
Yup that's how it is set up. I've ran a deployment and it's pulled through all the dashboard changes and the router (thanks!) but there is still some weird css thing going on which I need to investigate

**Comment by tomcwxyz** [comment]
Fixed
